const q=(key,text,options,extra={})=>({key,q:text,options:options.map((text,i)=>typeof text==='string'?{text}:text),...extra});
const questions=[
q('elapsed','彼と別れてから、<br>どのくらい経ちますか？',['1ヶ月未満','1〜3ヶ月','3〜6ヶ月','6ヶ月〜1年','1年以上','まだ正式には別れていない']),
q('contact','今、彼との連絡や接点は<br>どのような状態ですか？',[{text:'LINEで連絡できる',r:0},{text:'LINE以外のSNSや電話で連絡できる',r:0},{text:'職場・学校・共通の知人など接点がある',r:1},{text:'連絡先は分かるけど、今は連絡しづらい',r:2},{text:'ブロックされていて直接連絡できない',r:3,f:'blocked'},{text:'連絡先や現在いる場所が分からない',r:3,f:'no_contact'}]),
q('reply','彼とのやり取りで、<br>今一番近いものはどれですか？',[{text:'彼から連絡が来ることもある',r:0},{text:'こちらから送れば普通に返信が来る',r:0},{text:'用事がある時なら返信が来る',r:1},{text:'返信は遅いけど返ってくる',r:1},{text:'既読・未読スルーが多い',r:2},{text:'「連絡しないで」と言われている',r:3,f:'refused'},{text:'別れてからまだ連絡していない',r:2}]),
q('meeting','今、彼と会う関係について<br>一番近いものはどれですか？',[{text:'今も2人で会うことがある',m:0,f:'meeting'},{text:'誘えば会える可能性は高い',m:0},{text:'職場・学校などでは会う',m:2},{text:'連絡はできるけど、2人では会えていない',m:2},{text:'誘ったけど断られたことがある',m:3},{text:'今は会える状況ではない',m:3}]),
q('status','現在のお二人の状況で、<br>一番近いものを教えてください。',['お互い特定の交際相手はいない',{text:'彼に気になる女性がいる可能性がある',f:'possible_other'},{text:'彼に新しい恋人がいる',f:'new_partner'},{text:'自分に現在交際相手がいる',f:'user_partner'},{text:'自分または彼のどちらかが既婚',f:'married'},{text:'お互いに既婚',f:'married'},{text:'分からない',f:'unknown'}]),
q('pattern','付き合っていた時の自分に、<br>一番近いものはどれですか？',[{text:'不安になると彼を求めすぎていた',h:2,t:'abandonment_anxiety'},{text:'彼の気持ちを何度も確認したくなっていた',h:2,t:'love_confirmation'},{text:'喧嘩になると感情的になっていた',h:2,t:'emotional_reactivity'},{text:'嫌われるのが怖くて我慢することが多かった',h:2,t:'self_suppression'},{text:'彼に合わせすぎて自分らしくいられなかった',h:2,t:'over_adaptation'},{text:'本音を上手く伝えられなかった',h:1,t:'self_suppression'},{text:'自分側より、仕事・遠距離など環境的な問題が大きかった',h:0},{text:'自分ではまだよく分からない',h:1}]),
q('actions','別れたあとにしたことで、<br>当てはまるものを教えてください。',[{text:'距離を置いている',h:0},{text:'ときどき自然に連絡している',h:0},{text:'復縁したい気持ちを一度伝えた',h:1},{text:'何度か復縁をお願いした',h:2,t:'love_confirmation'},{text:'返信がなくても続けて連絡した',h:2,t:'love_confirmation'},{text:'彼のSNSを何度も確認している',h:2,t:'monitoring_behavior'},{text:'会いに行ったり、会おうとした',h:2,t:'abandonment_anxiety'},{text:'特に何もしていない',h:0,x:true}],{multiple:true,note:'当てはまるものをすべて選んでください',cap:3}),
q('reaction','彼から返信がない時、<br>どんな反応が起きやすいですか？',[{text:'不安にはなるけど、自分の生活に戻れる',h:0},{text:'気にはなるけど、落ち着いて待てる',h:0},{text:'嫌われたかもと何度も考えてしまう',h:2,t:'abandonment_anxiety'},{text:'スマホやSNSを何度も確認してしまう',h:2,t:'monitoring_behavior'},{text:'追加でLINEしたくなる',h:2,t:'love_confirmation'},{text:'自分が何か悪いことをしたのか考え続ける',h:2,t:'self_suppression'},{text:'悲しさや怒りが強くなって彼を責めたくなる',h:3,t:'emotional_reactivity'}]),
q('axis','付き合っていた時の関係で、<br>一番近いものはどれですか？',[{text:'自分の意見も普通に伝えられていた',h:0},{text:'嫌なことがあっても話し合えていた',h:0},{text:'嫌われるのが怖くて彼に合わせることが多かった',h:2,t:'over_adaptation'},{text:'言いたいことを我慢することが多かった',h:2,t:'self_suppression'},{text:'彼の機嫌が悪いと、自分が何とかしないとと思っていた',h:2,t:'over_adaptation'},{text:'彼から愛されているか頻繁に不安になっていた',h:3,t:'love_confirmation'},{text:'彼中心の生活になっていた',h:3,t:'partner_centered'}]),
q('future','もし復縁できたら、<br>どんな2人になりたいですか？',['お互い本音を伝えられる関係','前と同じ問題を繰り返さない関係','お互いの生活も大切にできる関係','安心して一緒にいられる関係','結婚や将来まで考えられる関係','とにかくもう一度付き合いたい','まだそこまでは考えられない']),
q('repeat','これまでの恋愛も含めて、<br>思い当たるものはありますか？',[{text:'毎回似たような不安を感じることが多い',h:2,t:'abandonment_anxiety'},{text:'相手に合わせすぎてしまうことが多い',h:2,t:'over_adaptation'},{text:'相手の気持ちを確認したくなることが多い',h:2,t:'love_confirmation'},{text:'我慢して最後に爆発することがある',h:3,t:'emotional_reactivity'},{text:'過去の恋愛でも振り回されることが多かった',h:3,t:'partner_centered'},{text:'今回の彼との恋愛で初めて感じた',h:1},{text:'あまり思い当たらない',h:0}]),
q('recovery','今の毎日の過ごし方で、<br>一番近いものはどれですか？',[{text:'自分の仕事や趣味も普通に楽しめている',h:0},{text:'少しずつ自分の生活に戻れている',h:1},{text:'何をしていても彼のことを考えてしまう',h:2,t:'partner_centered'},{text:'SNSやLINEが気になって集中できない',h:2,t:'monitoring_behavior'},{text:'彼の反応次第で1日の気分がかなり変わる',h:3,t:'partner_centered'},{text:'今は自分が何をしたいのかも分からない',h:3,t:'partner_centered'}]),
q('words','復縁について彼から言われた言葉で、<br>一番近いものはどれですか？',[{text:'「また同じことになりそう」と言われた',u:3},{text:'「今は恋愛を考えられない」と言われた',u:2},{text:'「友達ならいい」と言われた',u:2},{text:'「もう好きじゃない」と言われた',u:3},{text:'「復縁はない」と言われた',u:3},{text:'復縁について特に話したことはない',u:1},{text:'否定的なことは特に言われていない',u:0}]),
q('quality','今の彼との会話や空気感で、<br>一番近いものはどれですか？',[{text:'彼から話題を広げてくれる',u:0,p:2},{text:'普通に楽しく話せる',u:0,p:2},{text:'前より少し距離が縮まっている感じがする',u:0,p:2},{text:'話せるけど友達っぽい',u:2},{text:'どこか警戒されている感じがする',u:3},{text:'そっけない・必要最低限',u:3},{text:'今は話したり会ったりしていない',u:3}]),
q('signals','今の彼の様子で、<br>当てはまるものを教えてください。',[{text:'彼から連絡してくることがある',p:1},{text:'質問をしてきたり、会話を続けようとしてくれる',p:1},{text:'彼から会おうとすることがある',p:2},{text:'付き合っていた頃の思い出を話すことがある',p:1},{text:'自分の変化について何か言われた',p:1},{text:'恋愛や自分の近況について話してくれる',p:1},{text:'一緒にいる時、楽しそう・居心地が良さそう',p:2},{text:'特に当てはまるものはない',x:true},{text:'今は判断できる接点がない',x:true}],{multiple:true,note:'当てはまるものをすべて選んでください'})];

const stages={reply:{label:'返信のブロックを整える段階',title:'まずは、自然に連絡を続けられる関係へ',img:'images/result-c-couple.png',copy:'今の2人は、まず「返したくない」から「返してもいい」と思ってもらえる関係に戻していく段階です。僕はこれを「返信のブロック」と呼んでいます。',flow:['自分のハートを整える','返信のブロックを外す','再会へ進む']},remeet:{label:'再会のブロックを整える段階',title:'次は、また2人で自然に会える関係へ',img:'images/result-a-couple.png',copy:'連絡できる状態から「また2人で会ってもいい」と思ってもらえる関係へ進める段階です。僕はこれを「再会のブロック」と呼んでいます。',flow:['自分のハートを整える','自然なやり取りを続ける','再会のブロックを外す']},reunion:{label:'復縁のブロックを整える段階',title:'「また同じことになりそう」を外すとき',img:'images/result-b-couple.png',copy:'連絡や再会よりも「もう一度付き合っても大丈夫」と感じてもらうことがポイントです。僕はこれを「復縁のブロック」と呼んでいます。',flow:['自分の変化を積み重ねる','彼に「前と違う」を体験してもらう','復縁のブロックを外す']},accelerator:{label:'復縁のアクセルを育てる段階',title:'「また一緒にいたい」を育てていくとき',img:'images/result-s-couple.png',copy:'今の2人は、マイナスを減らすだけでなく「また話したい」「また会いたい」というプラスの感情を育てていく段階に近づいています。',flow:['今の良い関係を保つ','一緒にいる心地よさを増やす','復縁のアクセルを育てる']}};
const hearts={steady:['比較的、自分の気持ちに戻れる状態です','彼の反応に不安になる瞬間はあっても、自分の生活や気持ちへ戻れる力があります。'],swayed:['彼の反応で、ハートが揺れやすい状態です','彼の反応が変わると不安が大きくなり、安心するために彼の気持ちを確かめたくなりやすい状態です。'],affected:['今は、彼の反応に気持ちが大きく左右されやすい状態です','返信や態度によって、その日の気持ちや生活まで変わりやすくなっています。焦って距離を縮める前に、自分のハートを自分で戻せる状態を作ることを優先しましょう。']};
const tagCopy={abandonment_anxiety:'「嫌われたかも」「置いていかれるかも」と考え始めた時に、不安が大きくなりやすいようです。',love_confirmation:'不安を感じた時、彼の言葉や返信で気持ちを確かめたくなりやすいようです。',over_adaptation:'嫌われないように彼へ合わせる中で、自分の気持ちを後回しにしやすかったようです。',self_suppression:'言いたいことを我慢したあと、自分の中で苦しさが大きくなりやすかったようです。',emotional_reactivity:'不安や悲しさが強い時、感情のまま反応しやすかったようです。',monitoring_behavior:'反応が見えない時、LINEやSNSを確認して安心を探したくなりやすいようです。',partner_centered:'彼の反応が、自分の1日や生活全体にまで影響しやすくなっているようです。'};

let current=0,answers=Array(15).fill(null),profile={},result,started=false,completed=false,timers=[];
const $=id=>document.getElementById(id),d={start:$('start-screen'),profile:$('profile-screen'),question:$('question-screen'),loading:$('loading-screen'),result:$('result-screen'),name:$('user-name-input'),age:$('user-age-input'),job:$('user-job-select'),error:$('profile-error'),num:$('q-num'),text:$('question-text'),note:$('question-note'),options:$('options-container'),next:$('multi-next-btn'),bar:$('progress-bar'),back:$('back-btn')};
function track(event,more={}){const e={event,timestamp:new Date().toISOString(),...more};window.dataLayer=window.dataLayer||[];window.dataLayer.push(e);try{const a=JSON.parse(localStorage.getItem('jiroDiagnosisEvents')||'[]');localStorage.setItem('jiroDiagnosisEvents',JSON.stringify([...a.slice(-199),e]))}catch(_){}}
function show(s){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));s.classList.add('active');scrollTo(0,0)}
function chosen(i){const v=answers[i];return questions[i].multiple?(v||[]).map(n=>questions[i].options[n]):v===null?[]:[questions[i].options[v]]}
function byKey(k){const i=questions.findIndex(x=>x.key===k);return chosen(i)[0]||{}}
function render(){const z=questions[current],sel=answers[current]||(z.multiple?[]:null);d.num.textContent=current+1;d.text.innerHTML=z.q;d.note.textContent=z.note||'';d.note.style.display=z.note?'block':'none';d.bar.style.width=`${(current+1)/15*100}%`;d.back.style.display=current?'block':'none';d.options.innerHTML='';z.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option-btn'+(z.multiple&&sel.includes(i)?' selected':'');b.textContent=o.text;b.onclick=()=>z.multiple?toggle(i):single(i);d.options.appendChild(b)});d.next.hidden=!z.multiple;if(z.multiple)d.next.disabled=!sel.length}
function single(i){answers[current]=i;track('question_answered',{question_number:current+1,question_key:questions[current].key});setTimeout(advance,160)}
function toggle(i){const z=questions[current],o=z.options[i];let s=Array.isArray(answers[current])?[...answers[current]]:[];if(o.x)s=s.includes(i)?[]:[i];else{s=s.filter(n=>!z.options[n].x);s=s.includes(i)?s.filter(n=>n!==i):[...s,i]}answers[current]=s;render()}
function advance(){if(++current<15)render();else finish()}
function calculate(){let hs=0,tags={},flags=new Set();questions.forEach((z,i)=>{const c=chosen(i),sum=c.reduce((n,o)=>n+(o.h||0),0);hs+=z.cap?Math.min(sum,z.cap):sum;c.forEach(o=>{if(o.t)tags[o.t]=(tags[o.t]||0)+1;if(o.f)flags.add(o.f)})});const hl=hs<=4?'steady':hs<=10?'swayed':'affected',rt=Math.max(byKey('contact').r||0,byKey('reply').r||0),mt=byKey('meeting').m||0,ut=Math.max(byKey('words').u||0,byKey('quality').u||0),ps=chosen(14).reduce((n,o)=>n+(o.p||0),0)+(byKey('quality').p||0);let st=rt>=2?'reply':mt>=2?'remeet':ut>=2||ps<3?'reunion':'accelerator';if(flags.has('meeting')&&st==='reply')st=ut>=2?'reunion':ps>=3?'accelerator':'reunion';const ex=[];if(['学生','パート・アルバイト','求職中','無職'].includes(profile.job))ex.push('職業:'+profile.job);if(flags.has('married'))ex.push('既婚関係');if(flags.has('no_contact'))ex.push('連絡経路なし');const sorted=Object.entries(tags).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);return{heart_score:hs,heart_level:hl,heart_tags:sorted,reply_block_status:rt>=2?'strong':rt?'partial':'weak',remeet_block_status:mt>=2?'strong':mt?'partial':'weak',reunion_block_status:ut>=2?'strong':ut?'partial':'weak',accelerator_status:ps>=4?'active':ps>=2?'emerging':'not_yet',current_stage:st,priority_block:hl==='affected'?'heart_first':st,relationship_complexity_flags:[...flags],result_variant:`${hl}_${st}`,hard_exclusions:ex,can_reply:!ex.length}}
function finish(){result=calculate();completed=true;track('diagnosis_complete',{heart_level:result.heart_level,current_stage:result.current_stage});show(d.loading);const a=[...document.querySelectorAll('.analysis-item')];a.forEach((x,i)=>x.classList.toggle('active',i===0));timers=[setTimeout(()=>a[1].classList.add('active'),600),setTimeout(()=>a[2].classList.add('active'),1200),setTimeout(showResult,1800)]}
function showResult(){const s=stages[result.current_stage],h=hearts[result.heart_level];$('result-stage').textContent=s.label;$('result-title').textContent=s.title;$('result-img').src=s.img;$('result-desc').textContent='復縁には、ただ待つ・すぐLINEを送るといった一つの正解ではなく、今の2人に合った順番があります。今回の回答から、その最初の場所を整理しました。';$('heart-heading').textContent=h[0];$('heart-copy').textContent=(tagCopy[result.heart_tags[0]]||'彼との関係だけでなく、自分の心の動きにも目を向けられています。')+h[1]+' 僕は、過去の経験や思い込みから生まれた満たされにくい部分を「ハートの欠け」と呼んでいます。性格の問題ではなく、整えていけるものです。';$('couple-heading').textContent=s.title;$('couple-copy').textContent=s.copy;$('priority-flow').innerHTML=s.flow.map((x,i)=>`<div class="priority-step"><span>${i+1}</span>${x}</div>${i<2?'<div class="priority-arrow">↓</div>':''}`).join('');$('priority-copy').textContent=result.heart_level==='affected'?'今は彼への行動を急ぐより、まず自分の生活と気持ちへ戻れる状態を作り、その後に2人側のブロックへ進む順番です。':'自分のハートを整えながら、今の2人が止まっているブロックを一つずつ進めていく順番です。';$('keyword-section').hidden=!result.can_reply;show(d.result);track('result_view',{heart_level:result.heart_level,current_stage:result.current_stage});send()}
function answerText(i){return chosen(i).map(o=>o.text).join('／')}function group(a,b){return Array.from({length:b-a+1},(_,n)=>`Q${a+n+1}:${answerText(a+n)}`).join('｜')}
function send(){const iframe=document.createElement('iframe'),form=document.createElement('form'),name='hidden_'+Date.now();iframe.name=name;iframe.style.display='none';form.action='https://docs.google.com/forms/d/e/1FAIpQLScQG2p7YdrsRRnE2Y8LSCMWKNTwpKdRfDLsorCwqzWxz61ONw/formResponse';form.method='POST';form.target=name;form.style.display='none';const summary=[`heart_score:${result.heart_score}`,`heart_level:${result.heart_level}`,`heart_tags:${result.heart_tags.join(',')||'none'}`,`reply:${result.reply_block_status}`,`remeet:${result.remeet_block_status}`,`reunion:${result.reunion_block_status}`,`accelerator:${result.accelerator_status}`,`current_stage:${result.current_stage}`,`priority:${result.priority_block}`,`complexity:${result.relationship_complexity_flags.join(',')||'none'}`,`variant:${result.result_variant}`,`CTA:${result.can_reply?'私の現在地':'なし'}`,`除外:${result.hard_exclusions.join('/')||'なし'}`].join('｜');const data={'entry.808125093':profile.name,'entry.1761508389':`年齢:${profile.age}｜職業:${profile.job}`,'entry.1005036062':group(0,2),'entry.199990545':group(3,4),'entry.838626022':group(5,6),'entry.1200021442':group(7,9),'entry.1848582778':group(10,12),'entry.1178729743':group(13,14),'entry.721169860':summary};Object.entries(data).forEach(([n,v])=>{const i=document.createElement('input');i.name=n;i.value=v;form.appendChild(i)});document.body.append(iframe,form);form.submit();setTimeout(()=>{form.remove();iframe.remove()},2500)}
document.addEventListener('DOMContentLoaded',()=>{track('diagnosis_view');$('start-btn').onclick=()=>show(d.profile);$('next-to-q-btn').onclick=()=>{const name=d.name.value.trim(),age=Number(d.age.value),job=d.job.value;if(!name)return d.error.textContent='公式LINEで使用しているお名前を入力してください。';if(!Number.isInteger(age)||age<15||age>99)return d.error.textContent='年齢を半角数字で入力してください。';if(!job)return d.error.textContent='現在のお仕事を選択してください。';profile={name,age,job};d.error.textContent='';current=0;answers=Array(15).fill(null);started=true;track('diagnosis_start');render();show(d.question)};d.next.onclick=()=>{if(!answers[current]?.length)return;track('question_answered',{question_number:current+1,question_key:questions[current].key});advance()};d.back.onclick=()=>{if(current){track('question_back',{from_question:current+1});current--;render()}else show(d.profile)};$('copy-keyword-btn').onclick=async()=>{try{await navigator.clipboard.writeText('私の現在地')}catch(_){prompt('この言葉をコピーしてください','私の現在地')}track('consultation_cta_click',{heart_level:result.heart_level,current_stage:result.current_stage});$('copy-status').textContent='「私の現在地」をコピーしました。公式LINEに戻って送ってください。'};$('close-btn').onclick=()=>window.close();addEventListener('pagehide',()=>{if(started&&!completed)track('diagnosis_abandon',{question_number:current+1})})});
